export const GET_HOTELS_PROGRESS = 'GET_HOTELS_PROGRESS';
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTELS_EMPTY = 'GET_HOTELS_EMPTY';
export const FILTER_HOTELS_BY_NAME = 'FILTER_HOTELS_BY_NAME';
export const FILTER_HOTELS_BY_STARS = 'FILTER_HOTELS_BY_STARS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
